// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	feedbacks "lapakUmkm/features/feedbacks"

	mock "github.com/stretchr/testify/mock"
)

// FeedbackServiceInterface is an autogenerated mock type for the FeedbackServiceInterface type
type FeedbackServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: feedbackEntity
func (_m *FeedbackServiceInterface) Create(feedbackEntity feedbacks.FeedbackEntity) (feedbacks.FeedbackEntity, error) {
	ret := _m.Called(feedbackEntity)

	var r0 feedbacks.FeedbackEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(feedbacks.FeedbackEntity) (feedbacks.FeedbackEntity, error)); ok {
		return rf(feedbackEntity)
	}
	if rf, ok := ret.Get(0).(func(feedbacks.FeedbackEntity) feedbacks.FeedbackEntity); ok {
		r0 = rf(feedbackEntity)
	} else {
		r0 = ret.Get(0).(feedbacks.FeedbackEntity)
	}

	if rf, ok := ret.Get(1).(func(feedbacks.FeedbackEntity) error); ok {
		r1 = rf(feedbackEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id, userId
func (_m *FeedbackServiceInterface) Delete(id uint, userId uint) error {
	ret := _m.Called(id, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(id, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: id
func (_m *FeedbackServiceInterface) GetById(id uint) (feedbacks.FeedbackEntity, error) {
	ret := _m.Called(id)

	var r0 feedbacks.FeedbackEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (feedbacks.FeedbackEntity, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) feedbacks.FeedbackEntity); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(feedbacks.FeedbackEntity)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFeedbackByDetailTransactionId provides a mock function with given fields: detailTransactionId
func (_m *FeedbackServiceInterface) GetFeedbackByDetailTransactionId(detailTransactionId uint) ([]feedbacks.FeedbackEntity, error) {
	ret := _m.Called(detailTransactionId)

	var r0 []feedbacks.FeedbackEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]feedbacks.FeedbackEntity, error)); ok {
		return rf(detailTransactionId)
	}
	if rf, ok := ret.Get(0).(func(uint) []feedbacks.FeedbackEntity); ok {
		r0 = rf(detailTransactionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]feedbacks.FeedbackEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(detailTransactionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFeedbackByProductId provides a mock function with given fields: productId
func (_m *FeedbackServiceInterface) GetFeedbackByProductId(productId uint) ([]feedbacks.FeedbackEntity, error) {
	ret := _m.Called(productId)

	var r0 []feedbacks.FeedbackEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]feedbacks.FeedbackEntity, error)); ok {
		return rf(productId)
	}
	if rf, ok := ret.Get(0).(func(uint) []feedbacks.FeedbackEntity); ok {
		r0 = rf(productId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]feedbacks.FeedbackEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(productId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MyAllFeedback provides a mock function with given fields: myId, userId
func (_m *FeedbackServiceInterface) MyAllFeedback(myId uint, userId uint) ([]feedbacks.FeedbackEntity, error) {
	ret := _m.Called(myId, userId)

	var r0 []feedbacks.FeedbackEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) ([]feedbacks.FeedbackEntity, error)); ok {
		return rf(myId, userId)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) []feedbacks.FeedbackEntity); ok {
		r0 = rf(myId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]feedbacks.FeedbackEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(myId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: feedbackEntity, id, userId
func (_m *FeedbackServiceInterface) Update(feedbackEntity feedbacks.FeedbackEntity, id uint, userId uint) (feedbacks.FeedbackEntity, error) {
	ret := _m.Called(feedbackEntity, id, userId)

	var r0 feedbacks.FeedbackEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(feedbacks.FeedbackEntity, uint, uint) (feedbacks.FeedbackEntity, error)); ok {
		return rf(feedbackEntity, id, userId)
	}
	if rf, ok := ret.Get(0).(func(feedbacks.FeedbackEntity, uint, uint) feedbacks.FeedbackEntity); ok {
		r0 = rf(feedbackEntity, id, userId)
	} else {
		r0 = ret.Get(0).(feedbacks.FeedbackEntity)
	}

	if rf, ok := ret.Get(1).(func(feedbacks.FeedbackEntity, uint, uint) error); ok {
		r1 = rf(feedbackEntity, id, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFeedbackServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewFeedbackServiceInterface creates a new instance of FeedbackServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFeedbackServiceInterface(t mockConstructorTestingTNewFeedbackServiceInterface) *FeedbackServiceInterface {
	mock := &FeedbackServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
