// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	productTransactions "lapakUmkm/features/productTransactions"

	mock "github.com/stretchr/testify/mock"
)

// ProductTransactionServiceInterface is an autogenerated mock type for the ProductTransactionServiceInterface type
type ProductTransactionServiceInterface struct {
	mock.Mock
}

// CallBackMidtrans provides a mock function with given fields: id, status
func (_m *ProductTransactionServiceInterface) CallBackMidtrans(id uint, status string) error {
	ret := _m.Called(id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: transctionEntity
func (_m *ProductTransactionServiceInterface) Create(transctionEntity productTransactions.ProductTransactionEntity) (productTransactions.ProductTransactionEntity, error) {
	ret := _m.Called(transctionEntity)

	var r0 productTransactions.ProductTransactionEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(productTransactions.ProductTransactionEntity) (productTransactions.ProductTransactionEntity, error)); ok {
		return rf(transctionEntity)
	}
	if rf, ok := ret.Get(0).(func(productTransactions.ProductTransactionEntity) productTransactions.ProductTransactionEntity); ok {
		r0 = rf(transctionEntity)
	} else {
		r0 = ret.Get(0).(productTransactions.ProductTransactionEntity)
	}

	if rf, ok := ret.Get(1).(func(productTransactions.ProductTransactionEntity) error); ok {
		r1 = rf(transctionEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *ProductTransactionServiceInterface) GetById(id uint) (productTransactions.ProductTransactionEntity, error) {
	ret := _m.Called(id)

	var r0 productTransactions.ProductTransactionEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (productTransactions.ProductTransactionEntity, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) productTransactions.ProductTransactionEntity); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(productTransactions.ProductTransactionEntity)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MyTransactionHistory provides a mock function with given fields: myId, userId
func (_m *ProductTransactionServiceInterface) MyTransactionHistory(myId uint, userId uint) ([]productTransactions.ProductTransactionEntity, error) {
	ret := _m.Called(myId, userId)

	var r0 []productTransactions.ProductTransactionEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) ([]productTransactions.ProductTransactionEntity, error)); ok {
		return rf(myId, userId)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) []productTransactions.ProductTransactionEntity); ok {
		r0 = rf(myId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]productTransactions.ProductTransactionEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(myId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProductTransactionServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductTransactionServiceInterface creates a new instance of ProductTransactionServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductTransactionServiceInterface(t mockConstructorTestingTNewProductTransactionServiceInterface) *ProductTransactionServiceInterface {
	mock := &ProductTransactionServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
